name: Run Web Scraper

on:
  schedule:
    # Run every 10 minutes between 3:00 AM and 4:00 PM UTC (8:30 AM to 9:30 PM IST)
    - cron: "0-59/10 3-15 * * *"  # 3 AM to 3:59 PM UTC
    - cron: "0-40/10 16 * * *"     # 4:00 PM to 4:40 PM UTC
  workflow_dispatch: # Enable manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python app.py
